# Generated by Django 3.2.9 on 2022-01-15 20:13

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopuser",
            name="activation_key",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Ключ активации"
            ),
        ),
        migrations.AddField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=authapp.models.default_key_expiration_date,
                verbose_name="Активация истекает",
            ),
        ),
    ]
