# Generated by Django 3.2.9 on 2022-01-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0004_alter_shopuser_age"),
        ("authapp", "0004_shopuserprofile"),
    ]

    operations = []
